CONVERT_TO          = promicro_rp2040
PIN_COMPATIBLE      = promicro
BOOTLOADER          = rp2040
MOUSEKEY_ENABLE     = no     # Mouse keys
RGB_MATRIX_ENABLE   = no
LTO_ENABLE          = yes
COMBO_ENABLE 		= no
COMMAND_ENABLE      = no
AUTO_SHIFT_ENABLE   = no
CAPS_WORD_ENABLE    = yes
SRC += oneshot.c
SRC += swapper.c
SRC += layer_lock.c
